### ISSUE TITLE
Readme doesn't describe the api of this module

### ISSUE THREAD

**Issue by pietgeursen** [ssbc/ssb-validate#15]
I want to work on making native bindings for @AljoschaMeyer's work. 
I think this is the best place for me to start working.

And it's _so_ frustrating that there isn't a description of the api for this module.

What are the functions I can call?
What do I pass them?
What do they return?
Which ones can throw?

It looks like it exports:
`id`
`append`
`appendNew`
`append_kvt`
`create`
`validate`
`toKeyValueTimestamp`
`queue`
`checkInvalid`
`checkInvalidCheap`
`initial`

What's the difference between:
`append`
`appendNew`
`append_kvt`

Also `append_kvt` should probably be renamed to `appendKVT`. As well as explaining that kvt stands for Key Value Timestamp. (Again I spent a while wondering what it stood for, had to go reading the code)

What's the deal with `validate`?
It looks like it returns the state object or throws?

**Comment by AljoschaMeyer** [comment]
The simplest approach might be to just provide the low-level functions I outlined in the scuttleverse. In any case, I'd be weary of doing this convoluted high-level stuff without exposing the actual bread-and-butter functions.

**Comment by dominictarr** [comment]
sorry, I've been recovering from food poisoning today, otherwise I would have attended to this earlier. I pushed a version 4.0.1 that has documentation - TLDR, the main methods you really need to worry about is append and create. The others are mostly internal details which are exposed for testing.

**Comment by pietgeursen** [comment]
@dominictarr Thankyou thankyou! 
This is :100: times better.

Feel better.

**Comment by pietgeursen** [comment]
I spent a while reading the docs.

A couple of things that I think should still be added:

- A piece of example code for "ordinary" crypto mode.
  - It should probably explain what to do when an append fails (it throws right?) because if you try and append a forked feed (will happen occasionally) you don't want your whole program to explode.
- A piece of example code for "js" crypto mode which explains:
  - When you can use this optimisation
  - When you should _not_ use this optimisation
  - What security implications there are (if any). I was surprised that `validate` _only checks the last signature_ in the queue and then appends everything in the queue. It would to be good to explain why that's an ok thing to do. If this is trading off some security guarantees for speed then that should be made very explicit. 
  - Maybe link to where it actually gets used in the stack? If it does?
  - I think it could be good to move the js crypto functions into a separate section.

**Comment by dominictarr** [comment]
@pietgeursen I added some code examples in 4.0.3.
Also, I an explanation of the js mode stuff. I'd just about be inclined to remove that. It seemed like a good idea at the time, but we didn't actually end up using it and now we have wasm crypto, so I think it could probably just be removed.

**Comment by dominictarr** [comment]
@AljoschaMeyer 
> The simplest approach might be to just provide the low-level functions I outlined in the scuttleverse.

I'm not sure which functions you are refering to. Can you give me a link?

**Comment by pietgeursen** [comment]
Looking _heaps_ more betterer @dominictarr.

Re Aljoscha's comment: It's about the rust binding stuff. It's not important for this issue. We just had a call and talked about it so I'd say don't worry about it.
